# Define the program language and enviroments to run through travis
language: java
jdk: oraclejdk8

# Installs tomcat Loads in the deploy.sh script from root.
before_script:
- chmod +x ./deploy.sh
- chmod +x ./tomcat.sh

before_install:
- ./tomcat.sh

# Override the normal script mvn test -B, runs the script loaded from the script above
script:
- ./deploy.sh