language: java
jdk: oraclejdk8
script:
- mvn clean verify site -X

env:
  global:
    secure: N5etE0kqDcg+p1GJk+/B5gcK70Orf3JtLB4fHjV8nis1B+yxKNBYQg7iJzNiS88kWz9uHl3k5GBXroJc4unrO5sYz0nBNt7cGfJJClvwDSCyi3LRTWG7KGLsBeD4ihfwqBxRZfGFh0DHAW/o3Ys4SYjv2XqaIYF3PB4X1zevYdnfIkhEFXLNVUSYBP0r4trhCoZK9oxFYQGyVkj2fuNnT0wP6jmyA4NDoUxd1V00Gf9Esuuof8jcg3CcVOzeXO2yhwLP6VqIDlPRGszaCs6RWOErsXawi2YmBXbOSPkcpzwowb778i8rN9X7tb79KFbAqlIfSYzygbc4eti885SOdibczEjXHoyOu+mxWQd65TVHnWgHjbBiWGb3zhmaZ7W5Ifvd/R8L6TKF5yNQXajn4MwBpr5WXbmDurzbEOIqCfYrq6tTcsil8Hv5nuds/XFPp6LiRc0hibLlY7gNf3mz38c6dzrlWeeDPvZwDIUvqcfzGWVTXv5aJXVX+l+AiOvZTPR2njeZFFbToZw+J1D70rQe72somjIPsm7GwMQ/5m7frxvn8OJz+G7ZmD5QNZLwcgoLZ/glj6ZpQZ51qNzu4d0jDjnhLzCydcWh+azHreDWxjkMhI+Ygrb1MqaUvS2FzrnEVhm205PGEytqwzUtLLe9FJOBHMb/Bzl+2WjvLSg=
